# Generated by Django 5.1.2 on 2024-10-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_remove_loan_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='observations',
            field=models.TextField(default='Sem descrição.'),
        ),
    ]
